### ISSUE TITLE
Pol.is not working on "tintin"

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/osp-app#14]
<img width="948" alt="capture d ecran 2018-02-21 a 13 49 09" src="https://user-images.githubusercontent.com/29771726/36483178-ba859992-1715-11e8-9a45-deca82edfb68.png">

Peut-être car polis.site_id (caché dans le fichier de config ici: https://github.com/OpenSourcePolitics/osp-app/blob/alt/bosa/config/polis.yml#L2 n'est pas configuré côté serveur
Il faut associer à des clefs `decidim_organizations.name` leurs valeurs `polis_site_id_XXXXXXXXXX", de cette manière:
```
default: &default
  enabled: true
  site_id: "polis_site_id_XXXXXXXXXX"
    "fedict" : "polis_site_id_XXXXXXXXXX"
    "bosa" : "polis_site_id_XXXXXXXXXX"
```

**Comment by moustachu** [comment]
Fixed on https://bosa.opensourcepolitics.eu/processes/test-intern/f/53/

@juliesimon To be closed
