### ISSUE TITLE
Les notifications ne s'affichent pas 

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/osp-app#16]
Aucune notification alors que je devrais en voir plusieurs

![capture d ecran 2018-02-22 a 10 13 06](https://user-images.githubusercontent.com/29771726/36529605-185f76e8-17b9-11e8-8488-f2b30ed3f479.png)

**Comment by juliesimon** [comment]
Related to OpenSourcePolitics/decidim-participations#77

**Comment by ludivinecp** [comment]
@juliesimon En fait ça n'a pas de lien
