### ISSUE TITLE
En tant que modérateur, impossible d'accéder aux processus sans module "participations"

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/osp-app#17]
Il suffit qu'un MOA/CPDP/modérateur soit invité sur un processus sans module participation d'activé pour que son accès aux processus plante. C'est un comportement logique pour CPDP/MOA, car ces rôles n'ont aucun droit hors module participation. Par contre, ça ne devrait pas planter pour le Modérateur (qui a les droits modérateurs classique + droits CPDP sur participations) qui devrait pourvoir être modérateur d'un processus où il n'y a que "propositions" d'activé, par exemple.

**Comment by ludivinecp** [comment]
https://github.com/OpenSourcePolitics/decidim-participations/pull/78
