### ISSUE TITLE
Erreur lors de la publication du module Exports

### ISSUE THREAD

**Issue by TeaMhild** [OpenSourcePolitics/osp-app#19]
1/ Lorsque j'ajoute la fonctionnalité "Exports" sur l'instance https://tintin.opensourcepolitics.eu/admin/participatory_processes/qwertydemo/features cela fonctionne, mais une fois que je "publie" la fonctionnalité le message d'erreur ci-dessous apparaît. Quand je le dépublie tout revient à la normal et fonctionne.
![capture d ecran 2018-02-23 a 15 07 17](https://user-images.githubusercontent.com/36668301/36598088-597b7a08-18ab-11e8-853e-bcc2cfa59021.png)

**Comment by juliesimon** [comment]
Oui, c'est parce qu'Export n'est pas une fonctionnalité en tant que telle, donc ne devrait pas apparaitre dans la liste des fonctionnalités à exporter. Il faudrait la supprimer de cette liste, cf. issue OpenSourcePolitics/decidim-user-export#1

@virgile-dev @ludivinecp on s'en occupe quand c'est plus calme ?
