### ISSUE TITLE
Move decidim-polis to it's own repo

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/osp-app#21]
We'd like to import this feature as a gem : https://github.com/OpenSourcePolitics/osp-app/tree/alt/bosa/decidim-polis in the osp-app

For the Pol.is feature to work (meaning that the script creates a conversation with the Pol.is account it's associated with and serves back an iframe) it needs a correct value in front of the `data-site_id` data attribute (one of the data attribute that is given to the script that return the pol.is iframe). As of now we hosted this value in this config file : https://github.com/OpenSourcePolitics/osp-app/blob/alt/bosa/config/polis.yml. 

What is needed now is a way of entering this info from the admin panel using in the settings section. That way each organization can have its own polis_site_id.

Here is a checklist of what we need to do to make it happen : 
- [x] Move the folders code to this new repo : https://github.com/OpenSourcePolitics/decidim-polis
- [x] Add an organization settings submenu to host the polis_site_id information ( @moustachu told me that you can add this menu item from the decidim-polis engine so please don't code it in /decidim or /osp-app ,  thank you !). Here is how it would look like : 
<img width="1280" alt="capture d ecran 2018-02-26 a 18 59 51" src="https://user-images.githubusercontent.com/11473995/36687371-b16a6f5a-1b29-11e8-80c1-e8442426d20c.png">

This new config page would need to have translation keys in French, in English and in Dutch : 

- Configuration Pol.is  --> Configuratie Pol.is (nl) / Pol.is configuration (en)
- Cet identifiant vous est unique, ne le partagez pas et ne le modifiez pas. -->  Deze identificatiecode is uniek voor u, niet delen of wijzigen. (nl) /  This is your unique id, don't share it or change it.  (en)
- Pensez à vous connecter à Pol.is pour que les liens directs vers l'interface d'administration de Pol.is fonctionnent. --> Vergeet niet om in te loggen bij Pol.is zo dat de directe links naar de Pol. is administratie interface werk. (nl) / Remember to log in to Pol.is so that the direct links to the Pol.is administration interface work. (en)

@hgueguen please let me know if this is enough explanation to complete the task.

**Comment by hgueguen** [comment]
>> https://github.com/OpenSourcePolitics/decidim-polis
