### ISSUE TITLE
Missing categories in Proposals export

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/osp-app#23]
Strange behavior on exports from ecrivons.angers.fr: category/name appears in the export from "Appel à idées Journée citoyenne" but remains blank in the export from "Budget participatif 2018". There is no obvious reason, as categories are well documented in the back-office. 

<img width="480" alt="capture d ecran 2018-03-09 a 15 39 28" src="https://user-images.githubusercontent.com/10398564/37212784-56d2a712-23b0-11e8-8284-410dd3eae60d.png">

<img width="485" alt="capture d ecran 2018-03-09 a 15 39 39" src="https://user-images.githubusercontent.com/10398564/37212786-58ca26bc-23b0-11e8-8215-6ad68f360522.png">

**Comment by juliesimon** [comment]
@valentinchaput we were never able to fix this, any news from them? Did they manage without the category names?
