### ISSUE TITLE
F - show social networks icons directly on page

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/osp-app#24]
For accessibility reasons, BOSA wants the icons that allow a user to share on social medias to be accessible directly on the page and not through a "Share" link.

The share-link is currently called through the `share_modal.html.erb`

How it is now :  
![icons social networks](https://user-images.githubusercontent.com/29771726/37393850-999a5606-2772-11e8-9022-197944da710b.png)

Design proposal 1:
![icones social networks 1](https://user-images.githubusercontent.com/29771726/37393857-9c795e30-2772-11e8-983a-8b87d8b062e2.png)

Design 2: 
![icones social network 2](https://user-images.githubusercontent.com/29771726/37393860-9de32e54-2772-11e8-8eaa-2721e392d036.png)

**Comment by juliesimon** [comment]
@valentinchaput @virgile-dev votre avis sur le design des boutons réseaux sociaux affichés directement sur la page ?

**Comment by valentinchaput** [comment]
Indiquer "Partagez sur" me paraît mieux

**Comment by juliesimon** [comment]
Dans ce cas là, on ne garderait pas la cohérence avec le "Intégrer" du dessous ? Et on indique "Intégrez" ? Mais c'est un peu étrange, non ?
