### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by bishalkc** [OpenSourcePolitics/osp-app#3]
I am trying to get some hands on with decidim as well, and while trying your docker-compose I get this 

(master)⚡ [1] % docker pull decidim/decidim:0.8.3                                                                                                                        ~/Code/personnel/decidim
Error response from daemon: manifest for decidim/decidim:0.8.3 not found

**Comment by virgile-dev** [comment]
Hey @bishalkc 
You should go ahead an ask on the decidim gitter : https://gitter.im/decidim/decidim
They'll probably be able to answer you.

**Comment by bishalkc** [comment]
Thank you!! I am now trying with your decidim-cndp repo.. This is just a learning experience for me and I want to deploy for a city as well.

**Comment by virgile-dev** [comment]
Hey @bishalkc 
You should use decidim's original code that way Decidim's core team will be able to answer your questions : https://github.com/decidim/decidim
Good luck with your project
