### ISSUE TITLE
Change translation for "Conditions d'inscriptions" --> "Inscriptions activées"

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/osp-app#30]
Done it on crowdin already, we should add it as override.
![capture d ecran 2018-04-06 a 12 25 08](https://user-images.githubusercontent.com/11473995/38416737-033ba38c-3996-11e8-9cd8-6e2bacbe2fd9.png)

**Comment by juliesimon** [comment]
Done !
As said on rocket chat, now we don't override translation on osp-app, we change them directly on OpenSourcePolitics/decidim on the `0.10-stable` branch (and those in 0.10-stable)
