### ISSUE TITLE
Icons not showing on Nancy on Firefox

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/osp-app#41]
https://nancy.opensourcepolitics.eu/admin/ 

SVG icons are not displayed on Firefox but it works on Chrome

**Comment by moustachu** [comment]
**To be remembered : **

`icons not showing on Firefox` --> probably a syntax error in the SVG file for icons after a merge :wink:

cf. https://github.com/OpenSourcePolitics/decidim/commit/13c0dbaad3dfb9d7e4e2728f4004923bb2a15460
