### ISSUE TITLE
Comment section doesn't show at all in IE (11) 

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/osp-app#43]
Possibly all instances affected. 
A fix was found on the 0.10 stable for bosa : https://github.com/OpenSourcePolitics/osp-app/tree/alt/bosa

@moustachu can you signal the patch that you made ?
@juliesimon let's get this ready for everyone.

**Comment by moustachu** [comment]
@virgile-dev Could be useful to add the link to the page where the bug has been detected so we can easily reproduce without finding the mail corresponding to this issue ;) 

https://participation.lillemetropole.fr/processes/alimentationenmetropole/f/65/

**Comment by moustachu** [comment]
The patch for the `0.10-trad-auto-merge` is here : 
https://github.com/OpenSourcePolitics/decidim/commit/516cb11a16cbb211c51645ff52ab21c02669afcc

and you have to _rebuild_  the comments JS engine with `npm run build:prod`

--> Need to ask on the main repo if it's a good fix or just a hack patch

**Comment by virgile-dev** [comment]
Yup sorry @moustachu. 
> Need to ask on the main repo if it's a good fix or just a hack patch
Do you want me to take care of that?
