### ISSUE TITLE
Module Processus : PB de duplication

### ISSUE THREAD

**Issue by TeaMhild** [OpenSourcePolitics/osp-app#7]
1/ Partie ADMIN : http://julie-osp-test.herokuapp.com/admin/participatory_processes --> Au moment de dupliquer un processus, l'instance duplique bien le processus mais elle duplique en double les sous-catégories. 

2/ PARTIE USER : Lorsque l'utilisateur veut écrire une nouvelle Participation, au moment où il doit sélectionner sa catégorie --> affichage en double des sous catégories.

![partie admin](https://user-images.githubusercontent.com/36668301/36433735-873b60ac-165d-11e8-8cb8-d30424c7bdb9.png)
![partie user](https://user-images.githubusercontent.com/36668301/36433736-8759207e-165d-11e8-873c-ac4007b2062f.png)

**Comment by juliesimon** [comment]
EDIT : ça marche mais pas de copie des sous categories
